defaults: &defaults
  allow_dynamic_fields: true
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: geo_demo_development

test:
  <<: *defaults
  database: geo_demo_test
